### ISSUE TITLE
log is incomplete when useing ngx.log() 

### ISSUE THREAD

**Issue by wangyinsheng** [openresty/lua-nginx-module#744]
hi there ,
  i am tring to show the variables by using ngx.log() .
  in the init_by_lua block, it works well.
  in the rewrite block it not works well,here is the code and log output

init_by_lua
> init_by_lua '
                local write_list = require "resty.mercury_init";
                local topic_write_list = write_list.topic_msg;
                ngx.log(ngx.ERR, "length of write_list: " .. #topic_write_list);
                ngx.log(ngx.ERR, "value of write_list at 1 " .. topic_write_list[1]);'

log output when start
> 2016/04/25 14:25:21 [notice] 5818#0: signal process started
2016/04/25 14:25:24 [error] 5819#0: [lua] [string "init_by_lua"]:4: length of write_list: 40
2016/04/25 14:25:24 [error] 5819#0: [lua] [string "init_by_lua"]:5: value of write_list at 1 ab.000001

rewrite block
> local write_list = require "resty.mercury_init";
local topic_write_list = write_list.topic_msg;
ngx.log(ngx.ERR, "..........................................");
ngx.log(ngx.ERR, "length of write list:" .. #topic_write_list);
ngx.log(ngx.ERR, "value of write list at 1:" .. topic_write_list[1]);

log output when request
> 2016/04/25 14:25:38 [error] 5834#0: *1 [lua] record_log.lua:223: .........................................., client: 192.168.162.16, request: "GET /test HTTP/1.1", host: "192.168.107.234"
2016/04/25 14:25:38 [error] 5834#0: *1 [lua] record_log.lua:224: length of write list:40, client: 192.168.162.16, request: "GET /test HTTP/1.1", host: "192.168.107.234"
, client: 192.168.162.16,request: "GET /test HTTP/1.1", host: "192.168.107.234"

the log is incomplete when execute `ngx.log(ngx.ERR, "value of write list at 1:" .. topic_write_list[1]);`
i just don't understand, it can log out the length but can not log out the content 
thank you for any suggestion

**Comment by agentzh** [comment]
@wangyinsheng Maybe your last `ngx.log` statement did not have a chance to execute at all? Will you prepare a minimal and self-contained example that I can easily run on my side and reproduce the issue easily on my side? Thanks!

**Comment by wangyinsheng** [comment]
The first and second 'ngx.log' start with date time when request,but the last 'ngx.log' start with ','
I will prepare a example later

**Comment by agentzh** [comment]
@wangyinsheng That looks strange. And yeah, we need a minimal and self-contained example.

**Comment by wangyinsheng** [comment]
here is the example, the version of openresty is 1.2.8.6
`init_by_lua` block will load a white-list file which use absolute directory `/export/servers/openresty/nginx/conf/white-list` , you need change it or just unzip the tar file into `/export/servers/`

[openresty.tar.gz](https://github.com/openresty/lua-nginx-module/files/235771/openresty.tar.gz)

**Comment by agentzh** [comment]
@wangyinsheng Will you try minimizing it? Your 7.1MB tarball freak me out :)

Also, please try removing hard-coded file paths. You could have used relative paths instead ;)

Also, OpenResty 1.2.8.6 is ancient. It was released on 10 June 2013. I cannot remember how many bugs have been fixed since then. Please upgrade to the latest 1.9.7.4 release.

**Comment by wangyinsheng** [comment]
hi there , now only two files, both should be placed in `openresty/nginx/conf`, and i update the version to the 1.9.7.4, it still the same 
[conf.zip](https://github.com/openresty/lua-nginx-module/files/237793/conf.zip)

**Comment by agentzh** [comment]
@wangyinsheng I've tried your example and it works correctly. I think it is because you are displaying your error log messages on your terminal so the extra carriage return character (`\r`, ASCII code 13) confuses you. Try removing the carriage return characters from your white-list file, for example, using the `dos2unix` command:

```
dos2unix conf/white-list
```

**Comment by wangyinsheng** [comment]
Yeah,it works,thanks a lot! 
It's uneasy to find the reason ,so it's there any tools that can add debug points and show value of variables?

**Comment by agentzh** [comment]
@wangyinsheng Well, it's easy for me though. I used vim to view the log messages, which can display special characters visually (`\r` is displayed as `^M` in the vim terminal). Displaying directly on the terminal can do fancy stuff with those non-printable characters. Always be careful.

**Comment by agentzh** [comment]
@wangyinsheng Alternatively you can use lua-cjson or something like that to serialize the value and output it to logs or somewhere like that.

**Comment by agentzh** [comment]
Both are easy enough to me.

**Comment by wangyinsheng** [comment]
Ok, I got it,both are easy way to see the real output,thanks a lot!
